---
- name: Login As Super User
  command: "oc login -u {{ admin_user }} -p {{ admin_password }}"
  when: cluster=="openshift"

- name: Add Privileged Policy
  command: "oc adm policy add-scc-to-user privileged -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"

- name: Add Hostmount-anyuid Policy
  command: "oc adm policy add-scc-to-user hostmount-anyuid -z kubevirt-infra -n {{ namespace }}"
  when: cluster=="openshift"

- name: Download Kubevirt Template
  get_url:
    url: "https://github.com/kubevirt/kubevirt/releases/download/{{ tag }}/kubevirt.yaml"
    dest: /tmp/kubevirt.yaml
  when: release

- name: Rendering Kubevirt Yaml
  template:
    src: kubevirt.yaml.j2
    dest: /tmp/kubevirt.yaml
  when: not release

- name: Create Kubevirt Resources
  command: oc create -f /tmp/kubevirt.yaml
  ignore_errors : true
